class TaqError(Exception):
    """Base exception for all TaQ errors."""

class ConfigError(TaqError): ...
class PlaybookError(TaqError): ...
class PlaybookNotFoundError(PlaybookError): ...
class StepExecutionError(PlaybookError): ...
class ScoringError(TaqError): ...
class QueryError(TaqError): ...
class DatabaseError(TaqError): ...
class LLMError(TaqError): ...
class ConnectorError(TaqError): ...
class ConnectorNotFoundError(ConnectorError): ...
